<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use App\Models\Alapanyag;

class CreateAlapanyagsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('alapanyags', function (Blueprint $table) {
            $table->string('megnevezes')->length(30)->unique();
            $table->timestamps();
        });

        Alapanyag::create(['megnevezes' => 'eper']);
        Alapanyag::create(['megnevezes' => 'eperszirup']);
        Alapanyag::create(['megnevezes' => 'ananászlé']);
        Alapanyag::create(['megnevezes' => 'citromlé']);
        Alapanyag::create(['megnevezes' => 'grapefruitlé']);
        Alapanyag::create(['megnevezes' => 'pépesített eper']);
        Alapanyag::create(['megnevezes' => 'alkoholmentes pezsgő']);
        Alapanyag::create(['megnevezes' => 'tojás']);
        Alapanyag::create(['megnevezes' => 'tojásfehérje']);
        Alapanyag::create(['megnevezes' => 'tojássárgája']);
        Alapanyag::create(['megnevezes' => 'főtt tojás']);
        Alapanyag::create(['megnevezes' => 'fürjtojás']);
        Alapanyag::create(['megnevezes' => 'vaj']);
        Alapanyag::create(['megnevezes' => 'kristálycukor']);
        Alapanyag::create(['megnevezes' => 'porcukor']);
        Alapanyag::create(['megnevezes' => 'só']);
        Alapanyag::create(['megnevezes' => 'szezámsó']);
        Alapanyag::create(['megnevezes' => 'fűszersó']);
        Alapanyag::create(['megnevezes' => 'himalája só']);
        Alapanyag::create(['megnevezes' => 'sóvirág']);
        Alapanyag::create(['megnevezes' => 'zellersó']);
        Alapanyag::create(['megnevezes' => 'kínai só']);
        Alapanyag::create(['megnevezes' => 'liszt']);
        Alapanyag::create(['megnevezes' => 'tejszín']);
        Alapanyag::create(['megnevezes' => 'köles']);
        Alapanyag::create(['megnevezes' => 'zab']);
        Alapanyag::create(['megnevezes' => 'hajdina']);
        Alapanyag::create(['megnevezes' => 'tönkölybúza']);
        Alapanyag::create(['megnevezes' => 'bulgur']);
        Alapanyag::create(['megnevezes' => 'vadrizs']);
        Alapanyag::create(['megnevezes' => 'basmati rizs']);
        Alapanyag::create(['megnevezes' => 'jázmin rizs']);
        Alapanyag::create(['megnevezes' => 'barna rizs']);
        Alapanyag::create(['megnevezes' => 'fehér rizs']);
        Alapanyag::create(['megnevezes' => 'quinoa']);
        Alapanyag::create(['megnevezes' => 'gersli']);
        Alapanyag::create(['megnevezes' => 'rozs']);
        Alapanyag::create(['megnevezes' => 'kukoricaliszt']);
        Alapanyag::create(['megnevezes' => 'kukoricakeményítő']);
        Alapanyag::create(['megnevezes' => 'kukoricadara']);
        Alapanyag::create(['megnevezes' => 'rizsliszt']);
        Alapanyag::create(['megnevezes' => 'burgonyaliszt']);
        Alapanyag::create(['megnevezes' => 'mandulaliszt']);
        Alapanyag::create(['megnevezes' => 'kendermagliszt']);
        Alapanyag::create(['megnevezes' => 'szezámliszt']);
        Alapanyag::create(['megnevezes' => 'búzadara']);
        Alapanyag::create(['megnevezes' => 'háztartási keksz']);
        Alapanyag::create(['megnevezes' => 'kekszmorzsa']);
        Alapanyag::create(['megnevezes' => 'étolaj']);
        Alapanyag::create(['megnevezes' => 'olívaolaj']);
        Alapanyag::create(['megnevezes' => 'oreo keksz']);
        Alapanyag::create(['megnevezes' => 'gyors rizs']);
        Alapanyag::create(['megnevezes' => 'rizottó rizs']);
        Alapanyag::create(['megnevezes' => 'sushi rizs']);
        Alapanyag::create(['megnevezes' => 'dió']);
        Alapanyag::create(['megnevezes' => 'földimogyoró']);
        Alapanyag::create(['megnevezes' => 'mandula']);
        Alapanyag::create(['megnevezes' => 'kesudió']);
        Alapanyag::create(['megnevezes' => 'gesztenye']);
        Alapanyag::create(['megnevezes' => 'makadámdió']);
        Alapanyag::create(['megnevezes' => 'pisztácia']);
        Alapanyag::create(['megnevezes' => 'törökmogyoró']);
        Alapanyag::create(['megnevezes' => 'brazil dió']);
        Alapanyag::create(['megnevezes' => 'pekándió']);
        Alapanyag::create(['megnevezes' => 'sótlan pisztácia']);
        Alapanyag::create(['megnevezes' => 'zöld mandula']);
        Alapanyag::create(['megnevezes' => 'sózott törökmogyoró']);
        Alapanyag::create(['megnevezes' => 'citrom']);
        Alapanyag::create(['megnevezes' => 'mangó']);
        Alapanyag::create(['megnevezes' => 'grépfrút']);
        Alapanyag::create(['megnevezes' => 'narancs']);
        Alapanyag::create(['megnevezes' => 'lime']);
        Alapanyag::create(['megnevezes' => 'banán']);
        Alapanyag::create(['megnevezes' => 'gránátalma']);
        Alapanyag::create(['megnevezes' => 'ananász']);
        Alapanyag::create(['megnevezes' => 'kivi']);
        Alapanyag::create(['megnevezes' => 'avokádó']);
        Alapanyag::create(['megnevezes' => 'füge']);
        Alapanyag::create(['megnevezes' => 'kókusz']);
        Alapanyag::create(['megnevezes' => 'datolya']);
        Alapanyag::create(['megnevezes' => 'pomelo']);
        Alapanyag::create(['megnevezes' => 'kumquat']);
        Alapanyag::create(['megnevezes' => 'mandarin']);
        Alapanyag::create(['megnevezes' => 'vérnarancs']);
        Alapanyag::create(['megnevezes' => 'áfonya']);
        Alapanyag::create(['megnevezes' => 'tőzegáfonya']);
        Alapanyag::create(['megnevezes' => 'szeder']);
        Alapanyag::create(['megnevezes' => 'piros ribizli']);
        Alapanyag::create(['megnevezes' => 'málna']);
        Alapanyag::create(['megnevezes' => 'feketeribizli']);
        Alapanyag::create(['megnevezes' => 'szőlő']);
        Alapanyag::create(['megnevezes' => 'egres']);
        Alapanyag::create(['megnevezes' => 'kékszőlő']);
        Alapanyag::create(['megnevezes' => 'bodzabogyó']);
        Alapanyag::create(['megnevezes' => 'vörösáfonya']);
        Alapanyag::create(['megnevezes' => 'feketeáfonya']);
        Alapanyag::create(['megnevezes' => 'som']);
        Alapanyag::create(['megnevezes' => 'szamóca']);
        Alapanyag::create(['megnevezes' => 'őszibarack']);
        Alapanyag::create(['megnevezes' => 'sárgabarack']);
        Alapanyag::create(['megnevezes' => 'meggy']);
        Alapanyag::create(['megnevezes' => 'szilva']);
        Alapanyag::create(['megnevezes' => 'cseresznye']);
        Alapanyag::create(['megnevezes' => 'nektarin']);
        Alapanyag::create(['megnevezes' => 'japánszilva']);
        Alapanyag::create(['megnevezes' => 'ringlószilva']);
        Alapanyag::create(['megnevezes' => 'cigánymeggy']);
        Alapanyag::create(['megnevezes' => 'shiitake gomba']);
        Alapanyag::create(['megnevezes' => 'savanyított gomba']);
        Alapanyag::create(['megnevezes' => 'fafülgomba']);
        Alapanyag::create(['megnevezes' => 'vargánya gomba']);
        Alapanyag::create(['megnevezes' => 'gomba']);
        Alapanyag::create(['megnevezes' => 'kucsmagomba']);
        Alapanyag::create(['megnevezes' => 'rókagomba']);
        Alapanyag::create(['megnevezes' => 'laskagomba']);
        Alapanyag::create(['megnevezes' => 'szarvasgomba']);
        Alapanyag::create(['megnevezes' => 'csiperkegomba']);
        Alapanyag::create(['megnevezes' => 'portobello gomba']);
        Alapanyag::create(['megnevezes' => 'galambgomba']);
        Alapanyag::create(['megnevezes' => 'sötét trombitagomba']);
        Alapanyag::create(['megnevezes' => 'szegfűgomba']);
        Alapanyag::create(['megnevezes' => 'fagomba']);
        Alapanyag::create(['megnevezes' => 'májusi pereszke']);
        Alapanyag::create(['megnevezes' => 'fenyőtinoru']);
        Alapanyag::create(['megnevezes' => 'gombakonzerv']);
        Alapanyag::create(['megnevezes' => 'szárított gomba']);
        Alapanyag::create(['megnevezes' => 'bárányhús']);
        Alapanyag::create(['megnevezes' => 'báránygerinc']);
        Alapanyag::create(['megnevezes' => 'bárányborda']);
        Alapanyag::create(['megnevezes' => 'báránykaraj']);
        Alapanyag::create(['megnevezes' => 'juhhús']);
        Alapanyag::create(['megnevezes' => 'báránycsülök']);
        Alapanyag::create(['megnevezes' => 'borjúhús']);
        Alapanyag::create(['megnevezes' => 'borjúcomb']);
        Alapanyag::create(['megnevezes' => 'borjúlábszár']);
        Alapanyag::create(['megnevezes' => 'borjúkaraj']);
        Alapanyag::create(['megnevezes' => 'borjúmáj']);
        Alapanyag::create(['megnevezes' => 'borjúbríz']);
        Alapanyag::create(['megnevezes' => 'csirke']);
        Alapanyag::create(['megnevezes' => 'csirkemáj']);
        Alapanyag::create(['megnevezes' => 'csirkezúza']);
        Alapanyag::create(['megnevezes' => 'csirkemell (csontos)']);
        Alapanyag::create(['megnevezes' => 'csirkecomb']);
        Alapanyag::create(['megnevezes' => 'csirkeszárny']);
        Alapanyag::create(['megnevezes' => 'csirke alsócomb']);
        Alapanyag::create(['megnevezes' => 'csirke felsőcomb']);
        Alapanyag::create(['megnevezes' => 'csirkenyak']);
        Alapanyag::create(['megnevezes' => 'csirkeszív']);
        Alapanyag::create(['megnevezes' => 'csirkefarhát']);
        Alapanyag::create(['megnevezes' => 'tyúk']);
        Alapanyag::create(['megnevezes' => 'csirkemellfilé']);
        Alapanyag::create(['megnevezes' => 'csirkeláb']);
        Alapanyag::create(['megnevezes' => 'tyúkháj']);
        Alapanyag::create(['megnevezes' => 'gyöngytyúk']);
        Alapanyag::create(['megnevezes' => 'csirkeaprólék']);
        Alapanyag::create(['megnevezes' => 'éticsiga']);
        Alapanyag::create(['megnevezes' => 'galambmáj']);
        Alapanyag::create(['megnevezes' => 'kakas']);
        Alapanyag::create(['megnevezes' => 'galamb']);
        Alapanyag::create(['megnevezes' => 'levescsont']);
        Alapanyag::create(['megnevezes' => 'muflon']);
        Alapanyag::create(['megnevezes' => 'sült szöcske']);
        Alapanyag::create(['megnevezes' => 'kenguruhús']);
        Alapanyag::create(['megnevezes' => 'kacsahús']);
        Alapanyag::create(['megnevezes' => 'kacsamáj']);
        Alapanyag::create(['megnevezes' => 'kacsamell']);
        Alapanyag::create(['megnevezes' => 'kacsacomb']);
        Alapanyag::create(['megnevezes' => 'kacsazúza']);
        Alapanyag::create(['megnevezes' => 'vadkacsamell']);
        Alapanyag::create(['megnevezes' => 'némakacsa']);
        Alapanyag::create(['megnevezes' => 'némakacsa melle']);
        Alapanyag::create(['megnevezes' => 'kacsaaprólék']);
        Alapanyag::create(['megnevezes' => 'kecskehús']);
        Alapanyag::create(['megnevezes' => 'libahús']);
        Alapanyag::create(['megnevezes' => 'libamáj']);
        Alapanyag::create(['megnevezes' => 'libamell']);
        Alapanyag::create(['megnevezes' => 'libacomb']);
        Alapanyag::create(['megnevezes' => 'libaszív']);
        Alapanyag::create(['megnevezes' => 'libanyak bőr']);
        Alapanyag::create(['megnevezes' => 'libaaprólék']);
        Alapanyag::create(['megnevezes' => 'füstölt libamell']);
        Alapanyag::create(['megnevezes' => 'mangalica hús']);
        Alapanyag::create(['megnevezes' => 'mangalicaszűz']);
        Alapanyag::create(['megnevezes' => 'mangalicatarja']);
        Alapanyag::create(['megnevezes' => 'marhahús']);
        Alapanyag::create(['megnevezes' => 'pacal']);
        Alapanyag::create(['megnevezes' => 'darált marhahús']);
        Alapanyag::create(['megnevezes' => 'marharostélyos']);
        Alapanyag::create(['megnevezes' => 'marhabélszín']);
        Alapanyag::create(['megnevezes' => 'marhalapocka']);
        Alapanyag::create(['megnevezes' => 'marhalábszár']);
        Alapanyag::create(['megnevezes' => 'marhacomb']);
        Alapanyag::create(['megnevezes' => 'marhacsont']);
        Alapanyag::create(['megnevezes' => 'marhafartő']);
        Alapanyag::create(['megnevezes' => 'fehérpecsenye']);
        Alapanyag::create(['megnevezes' => 'marha velőscsont']);
        Alapanyag::create(['megnevezes' => 'marha hátszín']);
        Alapanyag::create(['megnevezes' => 'marhafarok']);
        Alapanyag::create(['megnevezes' => 'marhamáj']);
        Alapanyag::create(['megnevezes' => 'marhavelő']);
        Alapanyag::create(['megnevezes' => 'marhafelsál']);
        Alapanyag::create(['megnevezes' => 'marhanyelv']);
        Alapanyag::create(['megnevezes' => 'marhanyak']);
        Alapanyag::create(['megnevezes' => 'marhafaggyú']);
        Alapanyag::create(['megnevezes' => 'nyúlhús']);
        Alapanyag::create(['megnevezes' => 'nyúlcomb']);
        Alapanyag::create(['megnevezes' => 'nyúlmáj']);
        Alapanyag::create(['megnevezes' => 'pulykahús']);
        Alapanyag::create(['megnevezes' => 'pulykamáj']);
        Alapanyag::create(['megnevezes' => 'darált pulykahús']);
        Alapanyag::create(['megnevezes' => 'pulykamell']);
        Alapanyag::create(['megnevezes' => 'pulykacomb']);
        Alapanyag::create(['megnevezes' => 'pulykafelsőcomb']);
        Alapanyag::create(['megnevezes' => 'pulykazúza']);
        Alapanyag::create(['megnevezes' => 'pulykahere']);
        Alapanyag::create(['megnevezes' => 'bébipulyka']);
        Alapanyag::create(['megnevezes' => 'pulykanyak']);
        Alapanyag::create(['megnevezes' => 'sertéshús']);
        Alapanyag::create(['megnevezes' => 'sertésmáj']);
        Alapanyag::create(['megnevezes' => 'sertésháj']);
        Alapanyag::create(['megnevezes' => 'sertéscomb']);
        Alapanyag::create(['megnevezes' => 'sertésdagadó']);
        Alapanyag::create(['megnevezes' => 'csontos sertéskaraj']);
        Alapanyag::create(['megnevezes' => 'darált sertéshús']);
        Alapanyag::create(['megnevezes' => 'sertés rövidkaraj']);
        Alapanyag::create(['megnevezes' => 'sertés karajcsont']);
        Alapanyag::create(['megnevezes' => 'sertés szűzpecsenye']);
        Alapanyag::create(['megnevezes' => 'sertésoldalas']);
        Alapanyag::create(['megnevezes' => 'sertéstarja']);
        Alapanyag::create(['megnevezes' => 'sertésköröm']);
        Alapanyag::create(['megnevezes' => 'sertéscsülök']);
        Alapanyag::create(['megnevezes' => 'sertéslapocka']);
        Alapanyag::create(['megnevezes' => 'sertésfül']);
        Alapanyag::create(['megnevezes' => 'sertésborda']);
        Alapanyag::create(['megnevezes' => 'sertéscsont']);
        Alapanyag::create(['megnevezes' => 'sertésfarok']);
        Alapanyag::create(['megnevezes' => 'sertésorr']);
        Alapanyag::create(['megnevezes' => 'sertésvese']);
        Alapanyag::create(['megnevezes' => 'sertésszív']);
        Alapanyag::create(['megnevezes' => 'sertésnyelv']);
        Alapanyag::create(['megnevezes' => 'sertés agyvelő']);
        Alapanyag::create(['megnevezes' => 'sertésvelő']);
        Alapanyag::create(['megnevezes' => 'süldő malac']);
        Alapanyag::create(['megnevezes' => 'sertésvér']);
        Alapanyag::create(['megnevezes' => 'sertéstüdő']);
        Alapanyag::create(['megnevezes' => 'sertésbőrke']);
        Alapanyag::create(['megnevezes' => 'füstölt tarja']);
        Alapanyag::create(['megnevezes' => 'füstölt oldalas']);
        Alapanyag::create(['megnevezes' => 'füstölt sertéscsülök']);
        Alapanyag::create(['megnevezes' => 'sertésfej']);
        Alapanyag::create(['megnevezes' => 'sertésháló']);
        Alapanyag::create(['megnevezes' => 'vékonybél (sertés)']);
        Alapanyag::create(['megnevezes' => 'vaddisznóhús']);
        Alapanyag::create(['megnevezes' => 'őzhús']);
        Alapanyag::create(['megnevezes' => 'szarvashús']);
        Alapanyag::create(['megnevezes' => 'szarvasbélszín']);
        Alapanyag::create(['megnevezes' => 'őzgerinc']);
        Alapanyag::create(['megnevezes' => 'őzcomb']);
        Alapanyag::create(['megnevezes' => 'vaddisznószűz']);
        Alapanyag::create(['megnevezes' => 'vaddisznókaraj']);
        Alapanyag::create(['megnevezes' => 'szarvascomb']);
        Alapanyag::create(['megnevezes' => 'fácánhús']);
        Alapanyag::create(['megnevezes' => 'fürj']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('alapanyags');
    }
}
